CREATE TABLE IF NOT EXISTS public.dim_periodo
(
    "PERIODO" text COLLATE pg_catalog."default",
    "ANIO_PERIODO" text COLLATE pg_catalog."default",
    "ANIO" text COLLATE pg_catalog."default",
    "FECHA_INICIO" date,
    "FECHA_FIN" date,
    CONSTRAINT dim_periodo_pkey PRIMARY KEY ("ANIO_PERIODO")
    
);

CREATE TABLE IF NOT EXISTS public.dim_programa
(
    "ID_PROGRAMA" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_1" text COLLATE pg_catalog."default",
    "DESCRIPCION_NIVEL_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD_PROGRAMA_1" text COLLATE pg_catalog."default",
    "DESCRIPCION_FACULTAD_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_PROGRAMA_1" text COLLATE pg_catalog."default",
    "DESCRIPCION_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO_PROGRAMA_1" text COLLATE pg_catalog."default",
    "DESCRIPCION_DEPARTAMENTO_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_2" text COLLATE pg_catalog."default",
    "DESCRIPCION_NIVEL_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD_PROGRAMA_2" text COLLATE pg_catalog."default",
    "DESCRIPCION_FACULTAD_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_PROGRAMA_2" text COLLATE pg_catalog."default",
    "DESCRIPCION_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO_PROGRAMA_2" text COLLATE pg_catalog."default",
    "DESCRIPCION_DEPARTAMENTO_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_3" text COLLATE pg_catalog."default",
    "DESCRIPCION_NIVEL_PROGRAMA_3" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD_PROGRAMA_3" text COLLATE pg_catalog."default",
    "DESCRIPCION_FACULTAD_PROGRAMA_3" text COLLATE pg_catalog."default",
    "CODIGO_PROGRAMA_3" text COLLATE pg_catalog."default",
    "DESCRIPCION_PROGRAMA_3" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO_PROGRAMA_3" text COLLATE pg_catalog."default",
    "DESCRIPCION_DEPARTAMENTO_PROGRAMA_3" text COLLATE pg_catalog."default",
    CONSTRAINT dim_programa_pkey PRIMARY KEY ("ID_PROGRAMA")
);


CREATE TABLE IF NOT EXISTS public.dim_curso
(
    "ID_MATERIA" text COLLATE pg_catalog."default",
    "MATERIA" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD" text COLLATE pg_catalog."default",
    "DESCRIPCION_FACULTAD" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO" text COLLATE pg_catalog."default",
    "DESCRIPCION_DEPARTAMENTO" text COLLATE pg_catalog."default",
    "HORAS_CREDITO" text COLLATE pg_catalog."default",
    "NOMBRE_CURSO_LARGO" text COLLATE pg_catalog."default",
    "DESCRIPCION_MODO_DE_CALIFICACION" text COLLATE pg_catalog."default",
    "ATRIBUTO_SECCION" text COLLATE pg_catalog."default",
    "ATRIBUTO_CURSO" text COLLATE pg_catalog."default",
    "CODIGO_ASIGNATURA" text COLLATE pg_catalog."default",
    "NUMERO_CURSO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_curso_pkey PRIMARY KEY ("ID_MATERIA")
);

-- Table: public.dim_estudiantes

CREATE TABLE IF NOT EXISTS public.dim_estudiantes
(
    "PERIODO" text COLLATE pg_catalog."default",
    "PERIODO_EFF" text COLLATE pg_catalog."default",
    "DECISION_ADMISION" text COLLATE pg_catalog."default",
    "DESCRIPCION_DECISION_ADMISION" text COLLATE pg_catalog."default",
    "CODIGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "APELLIDOS" text COLLATE pg_catalog."default",
    "NOMBRES" text COLLATE pg_catalog."default",
    "TIPO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "TIPO_ESTUDIANTE_STDN" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ESTUDIANTE_STDN" text COLLATE pg_catalog."default",
    "TIPO_ADMISION" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ADMISION" text COLLATE pg_catalog."default",
    "ESTADO_ACADEMICO_INICIO_SEMESTRE" text COLLATE pg_catalog."default",
    "FECHA_NACIMIENTO"  text COLLATE pg_catalog."default",
    "CIUDAD_NACIMIENTO" text COLLATE pg_catalog."default",
    "NACIONALIDAD" text COLLATE pg_catalog."default",
    "DESCRIPCION_NACIONALIDAD" text COLLATE pg_catalog."default",
    "EDAD" text COLLATE pg_catalog."default",
    "SEXO" text COLLATE pg_catalog."default",
    "DESCRIPCION_SEXO" text COLLATE pg_catalog."default",
    "ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "DESCRIPCION_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "COHORTE" text COLLATE pg_catalog."default",
    "COHORTE_DESCRIPCION" text COLLATE pg_catalog."default",
    "DIRECCION" text COLLATE pg_catalog."default",
    "CIUDAD" text COLLATE pg_catalog."default",
    "CODIGO_CIUDAD" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO" text COLLATE pg_catalog."default",
    "CODIGO_PAIS" text COLLATE pg_catalog."default",
    "INDICATIVO" text COLLATE pg_catalog."default",
    "TELEFONO" text COLLATE pg_catalog."default",
    "EXTENSION" text COLLATE pg_catalog."default",
    "CELULAR" text COLLATE pg_catalog."default",
    "CORREO_PERSONAL" text COLLATE pg_catalog."default",
    "CORREO_UNIANDES" text COLLATE pg_catalog."default",
    "ALERTAS" text COLLATE pg_catalog."default",
    "ESTADO_ENTREGA_DOCUMENTOS_PG" text COLLATE pg_catalog."default",
    "OBSERVACIONES_DOCUMENTOS_ENTREGADOS_PG" text COLLATE pg_catalog."default",
    "ESTRATO" text COLLATE pg_catalog."default",
    "CODIGO_COLEGIO" text COLLATE pg_catalog."default",
    "CODIGO_DANE" text COLLATE pg_catalog."default",
    "NOMBRE_COLEGIO" text COLLATE pg_catalog."default",
    "CIUDAD_COLEGIO" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_COLEGIO" text COLLATE pg_catalog."default",
    "TIPO_COLEGIO" text COLLATE pg_catalog."default",
    "FECHA_GRADO_PG"  text COLLATE pg_catalog."default",
    "PEN_CURSO" text COLLATE pg_catalog."default",
    "PEN_POSC" text COLLATE pg_catalog."default",
    "PEN_TAM" text COLLATE pg_catalog."default",
    "PEN_PGA" text COLLATE pg_catalog."default",
    "UL_CURSO" text COLLATE pg_catalog."default",
    "UL_POSC" text COLLATE pg_catalog."default",
    "UL_TAM" text COLLATE pg_catalog."default",
    "UL_PGA" text COLLATE pg_catalog."default",
    "SE_HA_PRESENTADO" text COLLATE pg_catalog."default",
    "SE_HA_MATRICULADO" text COLLATE pg_catalog."default",
    "SOLICITA_APOYO_FINANCIERO" text COLLATE pg_catalog."default",
    "TIPO_EXAMEN" text COLLATE pg_catalog."default",
    "SNP" text COLLATE pg_catalog."default",
    "PUNTAJE" text COLLATE pg_catalog."default",
    "PLC" text COLLATE pg_catalog."default",
    "PMA" text COLLATE pg_catalog."default",
    "PSC" text COLLATE pg_catalog."default",
    "PCN" text COLLATE pg_catalog."default",
    "PIN" text COLLATE pg_catalog."default",
    "EXAMEN_INTERNO" text COLLATE pg_catalog."default",
    "EXAMEN_INTERNO_NOTA" text COLLATE pg_catalog."default",
    "EXAMEN_HOMOLOGABLE" text COLLATE pg_catalog."default",
    "PREGRADO_QS" text COLLATE pg_catalog."default",
    "PREGRADO_QS_UNI" text COLLATE pg_catalog."default",
    "PREGRADO_QS_VERFICADO" text COLLATE pg_catalog."default",
    "APELLIDOS_PADRE" text COLLATE pg_catalog."default",
    "NOMBRES_PADRE" text COLLATE pg_catalog."default",
    "DIRECCION_PADRE" text COLLATE pg_catalog."default",
    "CIUDAD_PADRE" text COLLATE pg_catalog."default",
    "INDICATIVO_PADRE" text COLLATE pg_catalog."default",
    "TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "CORREO_PADRE" text COLLATE pg_catalog."default",
    "APELLIDOS_MADRE" text COLLATE pg_catalog."default",
    "NOMBRES_MADRE" text COLLATE pg_catalog."default",
    "DIRECCION_MADRE" text COLLATE pg_catalog."default",
    "CIUDAD_MADRE" text COLLATE pg_catalog."default",
    "INDICATIVO_MADRE" text COLLATE pg_catalog."default",
    "TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "CORREO_MADRE" text COLLATE pg_catalog."default",
    "APELLIDOS_ACUDIENTE" text COLLATE pg_catalog."default",
    "NOMBRES_ACUDIENTE" text COLLATE pg_catalog."default",
    "DIRECCION_ACUDIENTE" text COLLATE pg_catalog."default",
    "CIUDAD_ACUDIENTE" text COLLATE pg_catalog."default",
    "INDICATIVO_ACUDIENTE" text COLLATE pg_catalog."default",
    "TELEFONO_ACUDIENTE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_ACUDIENTE" text COLLATE pg_catalog."default",
    "CORREO_ACUDIENTE" text COLLATE pg_catalog."default",
    "NUMERO_HERMANOS" text COLLATE pg_catalog."default",
    "POSICION_ENTRE_HERMANOS" text COLLATE pg_catalog."default",
    "ESTADO_CIVIL_PADRES" text COLLATE pg_catalog."default",
    "NIVEL_EDUCATIVO_MADRE" text COLLATE pg_catalog."default",
    "OCUPACION_MADRE" text COLLATE pg_catalog."default",
    "NIVEL_EDUCATIVO_PADRE" text COLLATE pg_catalog."default",
    "OCUPACION_PADRE" text COLLATE pg_catalog."default",
    "TIPO_VIVIENDA" text COLLATE pg_catalog."default",
    "CURSO_BACH_UN_COLEGIO" text COLLATE pg_catalog."default",
    "NUMERO_COLEGIOS_BACH" text COLLATE pg_catalog."default",
    "PERTENECE_MINORIA_ETNICA" text COLLATE pg_catalog."default",
    "SISBEN" text COLLATE pg_catalog."default",
    "PUN_SISBEN" text COLLATE pg_catalog."default",
    "CUMPLE_I1" text COLLATE pg_catalog."default",
    "CUMPLE_EI" text COLLATE pg_catalog."default",
    "CUMPLE_RANK" text COLLATE pg_catalog."default",
    "CUMPLE_PGA" text COLLATE pg_catalog."default",
    "CUMPLE_UNAL" text COLLATE pg_catalog."default",
    "CUMPLE_QS" text COLLATE pg_catalog."default",
    "FORMAS_ADMISION" text COLLATE pg_catalog."default",
    "FECHA_DOCUMENTOS"  text COLLATE pg_catalog."default",
    "INDICADOR_GRADUADO" text COLLATE pg_catalog."default",
    "ESTADO_ENTREGA_DOCUMENTOS_PS" text COLLATE pg_catalog."default",
    "OBERVACIONES_DOCUMENTOS_ENTREGADOS_PS" text COLLATE pg_catalog."default",
    "NOMBRE_EMPRESA_ESTUDIANTE" text COLLATE pg_catalog."default",
    "NOMBRE_SECTOR_EMPRESA_ESTUDIANTE" text COLLATE pg_catalog."default",
    "CARGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "DIRECCION_EMPRESA" text COLLATE pg_catalog."default",
    "CIUDAD_EMPRESA" text COLLATE pg_catalog."default",
    "PAIS_EMPRESA" text COLLATE pg_catalog."default",
    "INDICATIVO_EMPRESA" text COLLATE pg_catalog."default",
    "TELEFONO_EMPRESA" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_EMPRESA" text COLLATE pg_catalog."default",
    "UNIVERSIDAD_PREGRADO" text COLLATE pg_catalog."default",
    "CIUDAD_UNIVERSIDAD" text COLLATE pg_catalog."default",
    "PAIS_UNIVERSIDAD" text COLLATE pg_catalog."default",
    "FECHA_INICIO_PREGRADO" text COLLATE pg_catalog."default",
    "FECHA_FIN_PREGRADO" text COLLATE pg_catalog."default",
    "TITULO_OBTENIDO" text COLLATE pg_catalog."default",
    "PROMEDIO_ACUMULADO" text COLLATE pg_catalog."default",
    "FECHA_GRADO_PS" text COLLATE pg_catalog."default",
    "AREA_INVESTIGACION" text COLLATE pg_catalog."default",
    "INTERES_ACADEMICO" text COLLATE pg_catalog."default",
    "EXPERIENCIA_INVESTIGACION" text COLLATE pg_catalog."default",
    "EXPERIENCIA_LABORAL" text COLLATE pg_catalog."default",
    "DISTINCIONES" text COLLATE pg_catalog."default",
    "REFERENCIAS_ACADEMICAS" text COLLATE pg_catalog."default",
    "CONOCIMIENTOS_DEL_PROGRAMA" text COLLATE pg_catalog."default",
    "FORMA_DE_FINANCIACION" text COLLATE pg_catalog."default",
    "REQUIERE_APOYO_FINANCIERO" text COLLATE pg_catalog."default",
    "LENGUA_MATERNA" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_LECTURA" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_ESCRITO" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_ORAL" text COLLATE pg_catalog."default",
    "PORCENTAJE_TIEMPO_PARA_ESTUDIO" text COLLATE pg_catalog."default",
    "ENTREGO_HOJA_VIDA" text COLLATE pg_catalog."default",
    "ENTREGO_ACTA" text COLLATE pg_catalog."default",
    "ENTREGO_NOTAS_PREGRADO" text COLLATE pg_catalog."default",
    "MATRICULADO_BANNER" text COLLATE pg_catalog."default",
    "MATRICULADO_FINANCIERA" text COLLATE pg_catalog."default",
    "TIPO_FINANCIERA" text COLLATE pg_catalog."default",
    "TOTAL_PAGO_FINANCIERA" text COLLATE pg_catalog."default",
    "MANEJO_DATOS_SENSIBLES" text COLLATE pg_catalog."default",
    "CIUDAD_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "PAIS_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "EDAD_ADM" text COLLATE pg_catalog."default",
    "ESTADO_ACADEMICO_COMBINADO" text COLLATE pg_catalog."default",
    "INSCRITO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_estudiantes_pkey PRIMARY KEY ("CODIGO_ESTUDIANTE")
);

-- Table: public.dim_estudiantes_magister

CREATE TABLE IF NOT EXISTS public.dim_estudiantes_magister
(
    "PERIODO" text COLLATE pg_catalog."default",
    "PERIODO_EFF" text COLLATE pg_catalog."default",
    "DECISION_ADMISION" text COLLATE pg_catalog."default",
    "DESCRIPCION_DECISION_ADMISION" text COLLATE pg_catalog."default",
    "CODIGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "APELLIDOS" text COLLATE pg_catalog."default",
    "NOMBRES" text COLLATE pg_catalog."default",
    "TIPO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "TIPO_ESTUDIANTE_STDN" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ESTUDIANTE_STDN" text COLLATE pg_catalog."default",
    "TIPO_ADMISION" text COLLATE pg_catalog."default",
    "DESCRIPCION_TIPO_ADMISION" text COLLATE pg_catalog."default",
    "ESTADO_ACADEMICO_INICIO_SEMESTRE" text COLLATE pg_catalog."default",
    "FECHA_NACIMIENTO"  text COLLATE pg_catalog."default",
    "CIUDAD_NACIMIENTO" text COLLATE pg_catalog."default",
    "NACIONALIDAD" text COLLATE pg_catalog."default",
    "DESCRIPCION_NACIONALIDAD" text COLLATE pg_catalog."default",
    "EDAD" text COLLATE pg_catalog."default",
    "SEXO" text COLLATE pg_catalog."default",
    "DESCRIPCION_SEXO" text COLLATE pg_catalog."default",
    "ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "DESCRIPCION_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "COHORTE" text COLLATE pg_catalog."default",
    "COHORTE_DESCRIPCION" text COLLATE pg_catalog."default",
    "DIRECCION" text COLLATE pg_catalog."default",
    "CIUDAD" text COLLATE pg_catalog."default",
    "CODIGO_CIUDAD" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO" text COLLATE pg_catalog."default",
    "CODIGO_PAIS" text COLLATE pg_catalog."default",
    "INDICATIVO" text COLLATE pg_catalog."default",
    "TELEFONO" text COLLATE pg_catalog."default",
    "EXTENSION" text COLLATE pg_catalog."default",
    "CELULAR" text COLLATE pg_catalog."default",
    "CORREO_PERSONAL" text COLLATE pg_catalog."default",
    "CORREO_UNIANDES" text COLLATE pg_catalog."default",
    "ALERTAS" text COLLATE pg_catalog."default",
    "ESTADO_ENTREGA_DOCUMENTOS_PG" text COLLATE pg_catalog."default",
    "OBSERVACIONES_DOCUMENTOS_ENTREGADOS_PG" text COLLATE pg_catalog."default",
    "ESTRATO" text COLLATE pg_catalog."default",
    "CODIGO_COLEGIO" text COLLATE pg_catalog."default",
    "CODIGO_DANE" text COLLATE pg_catalog."default",
    "NOMBRE_COLEGIO" text COLLATE pg_catalog."default",
    "CIUDAD_COLEGIO" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_COLEGIO" text COLLATE pg_catalog."default",
    "TIPO_COLEGIO" text COLLATE pg_catalog."default",
    "FECHA_GRADO_PG" text COLLATE pg_catalog."default",
    "PEN_CURSO" text COLLATE pg_catalog."default",
    "PEN_POSC" text COLLATE pg_catalog."default",
    "PEN_TAM" text COLLATE pg_catalog."default",
    "PEN_PGA" text COLLATE pg_catalog."default",
    "UL_CURSO" text COLLATE pg_catalog."default",
    "UL_POSC" text COLLATE pg_catalog."default",
    "UL_TAM" text COLLATE pg_catalog."default",
    "UL_PGA" text COLLATE pg_catalog."default",
    "SE_HA_PRESENTADO" text COLLATE pg_catalog."default",
    "SE_HA_MATRICULADO" text COLLATE pg_catalog."default",
    "SOLICITA_APOYO_FINANCIERO" text COLLATE pg_catalog."default",
    "TIPO_EXAMEN" text COLLATE pg_catalog."default",
    "SNP" text COLLATE pg_catalog."default",
    "PUNTAJE" text COLLATE pg_catalog."default",
    "PLC" text COLLATE pg_catalog."default",
    "PMA" text COLLATE pg_catalog."default",
    "PSC" text COLLATE pg_catalog."default",
    "PCN" text COLLATE pg_catalog."default",
    "PIN" text COLLATE pg_catalog."default",
    "EXAMEN_INTERNO" text COLLATE pg_catalog."default",
    "EXAMEN_INTERNO_NOTA" text COLLATE pg_catalog."default",
    "EXAMEN_HOMOLOGABLE" text COLLATE pg_catalog."default",
    "PREGRADO_QS" text COLLATE pg_catalog."default",
    "PREGRADO_QS_UNI" text COLLATE pg_catalog."default",
    "PREGRADO_QS_VERFICADO" text COLLATE pg_catalog."default",
    "APELLIDOS_PADRE" text COLLATE pg_catalog."default",
    "NOMBRES_PADRE" text COLLATE pg_catalog."default",
    "DIRECCION_PADRE" text COLLATE pg_catalog."default",
    "CIUDAD_PADRE" text COLLATE pg_catalog."default",
    "INDICATIVO_PADRE" text COLLATE pg_catalog."default",
    "TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "CORREO_PADRE" text COLLATE pg_catalog."default",
    "APELLIDOS_MADRE" text COLLATE pg_catalog."default",
    "NOMBRES_MADRE" text COLLATE pg_catalog."default",
    "DIRECCION_MADRE" text COLLATE pg_catalog."default",
    "CIUDAD_MADRE" text COLLATE pg_catalog."default",
    "INDICATIVO_MADRE" text COLLATE pg_catalog."default",
    "TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "CORREO_MADRE" text COLLATE pg_catalog."default",
    "APELLIDOS_ACUDIENTE" text COLLATE pg_catalog."default",
    "NOMBRES_ACUDIENTE" text COLLATE pg_catalog."default",
    "DIRECCION_ACUDIENTE" text COLLATE pg_catalog."default",
    "CIUDAD_ACUDIENTE" text COLLATE pg_catalog."default",
    "INDICATIVO_ACUDIENTE" text COLLATE pg_catalog."default",
    "TELEFONO_ACUDIENTE" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_ACUDIENTE" text COLLATE pg_catalog."default",
    "CORREO_ACUDIENTE" text COLLATE pg_catalog."default",
    "NUMERO_HERMANOS" text COLLATE pg_catalog."default",
    "POSICION_ENTRE_HERMANOS" text COLLATE pg_catalog."default",
    "ESTADO_CIVIL_PADRES" text COLLATE pg_catalog."default",
    "NIVEL_EDUCATIVO_MADRE" text COLLATE pg_catalog."default",
    "OCUPACION_MADRE" text COLLATE pg_catalog."default",
    "NIVEL_EDUCATIVO_PADRE" text COLLATE pg_catalog."default",
    "OCUPACION_PADRE" text COLLATE pg_catalog."default",
    "TIPO_VIVIENDA" text COLLATE pg_catalog."default",
    "CURSO_BACH_UN_COLEGIO" text COLLATE pg_catalog."default",
    "NUMERO_COLEGIOS_BACH" text COLLATE pg_catalog."default",
    "PERTENECE_MINORIA_ETNICA" text COLLATE pg_catalog."default",
    "SISBEN" text COLLATE pg_catalog."default",
    "PUN_SISBEN" text COLLATE pg_catalog."default",
    "CUMPLE_I1" text COLLATE pg_catalog."default",
    "CUMPLE_EI" text COLLATE pg_catalog."default",
    "CUMPLE_RANK" text COLLATE pg_catalog."default",
    "CUMPLE_PGA" text COLLATE pg_catalog."default",
    "CUMPLE_UNAL" text COLLATE pg_catalog."default",
    "CUMPLE_QS" text COLLATE pg_catalog."default",
    "FORMAS_ADMISION" text COLLATE pg_catalog."default",
    "FECHA_DOCUMENTOS" text COLLATE pg_catalog."default",
    "INDICADOR_GRADUADO" text COLLATE pg_catalog."default",
    "ESTADO_ENTREGA_DOCUMENTOS_PS" text COLLATE pg_catalog."default",
    "OBERVACIONES_DOCUMENTOS_ENTREGADOS_PS" text COLLATE pg_catalog."default",
    "NOMBRE_EMPRESA_ESTUDIANTE" text COLLATE pg_catalog."default",
    "NOMBRE_SECTOR_EMPRESA_ESTUDIANTE" text COLLATE pg_catalog."default",
    "CARGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "DIRECCION_EMPRESA" text COLLATE pg_catalog."default",
    "CIUDAD_EMPRESA" text COLLATE pg_catalog."default",
    "PAIS_EMPRESA" text COLLATE pg_catalog."default",
    "INDICATIVO_EMPRESA" text COLLATE pg_catalog."default",
    "TELEFONO_EMPRESA" text COLLATE pg_catalog."default",
    "EXTENSION_TELEFONO_EMPRESA" text COLLATE pg_catalog."default",
    "UNIVERSIDAD_PREGRADO" text COLLATE pg_catalog."default",
    "CIUDAD_UNIVERSIDAD" text COLLATE pg_catalog."default",
    "PAIS_UNIVERSIDAD" text COLLATE pg_catalog."default",
    "FECHA_INICIO_PREGRADO"  text COLLATE pg_catalog."default",
    "FECHA_FIN_PREGRADO"  text COLLATE pg_catalog."default",
    "TITULO_OBTENIDO" text COLLATE pg_catalog."default",
    "PROMEDIO_ACUMULADO" text COLLATE pg_catalog."default",
    "FECHA_GRADO_PS" text COLLATE pg_catalog."default",
    "AREA_INVESTIGACION" text COLLATE pg_catalog."default",
    "INTERES_ACADEMICO" text COLLATE pg_catalog."default",
    "EXPERIENCIA_INVESTIGACION" text COLLATE pg_catalog."default",
    "EXPERIENCIA_LABORAL" text COLLATE pg_catalog."default",
    "DISTINCIONES" text COLLATE pg_catalog."default",
    "REFERENCIAS_ACADEMICAS" text COLLATE pg_catalog."default",
    "CONOCIMIENTOS_DEL_PROGRAMA" text COLLATE pg_catalog."default",
    "FORMA_DE_FINANCIACION" text COLLATE pg_catalog."default",
    "REQUIERE_APOYO_FINANCIERO" text COLLATE pg_catalog."default",
    "LENGUA_MATERNA" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_LECTURA" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_ESCRITO" text COLLATE pg_catalog."default",
    "NIVEL_INGLES_ORAL" text COLLATE pg_catalog."default",
    "PORCENTAJE_TIEMPO_PARA_ESTUDIO" text COLLATE pg_catalog."default",
    "ENTREGO_HOJA_VIDA" text COLLATE pg_catalog."default",
    "ENTREGO_ACTA" text COLLATE pg_catalog."default",
    "ENTREGO_NOTAS_PREGRADO" text COLLATE pg_catalog."default",
    "MATRICULADO_BANNER" text COLLATE pg_catalog."default",
    "MATRICULADO_FINANCIERA" text COLLATE pg_catalog."default",
    "TIPO_FINANCIERA" text COLLATE pg_catalog."default",
    "TOTAL_PAGO_FINANCIERA" text COLLATE pg_catalog."default",
    "MANEJO_DATOS_SENSIBLES" text COLLATE pg_catalog."default",
    "CIUDAD_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "PAIS_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "EDAD_ADM" text COLLATE pg_catalog."default",
    "ESTADO_ACADEMICO_COMBINADO" text COLLATE pg_catalog."default",
    "INSCRITO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_estudiantes_maestria_pkey PRIMARY KEY ("CODIGO_ESTUDIANTE")
);

CREATE TABLE IF NOT EXISTS public.dim_profesor
(
    "CODIGO_DOCENTE" text COLLATE pg_catalog."default",
    "INDICADOR_DOCENTE" text COLLATE pg_catalog."default",
    "INDICADOR_ASESOR" text COLLATE pg_catalog."default",
    "IDENTIFICACION" text COLLATE pg_catalog."default",
    "FACULTADES" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD" text COLLATE pg_catalog."default",
    "PIDM" integer,
    "PRIMER_NOMBRE" text COLLATE pg_catalog."default",
    "SEGUNDO_NOMBRE" text COLLATE pg_catalog."default",
    "NOMBRES" text COLLATE pg_catalog."default",
    "PRIMER_APELLIDO" text COLLATE pg_catalog."default",
    "SEGUNDO_APELLIDO" text COLLATE pg_catalog."default",
    "APELLIDOS" text COLLATE pg_catalog."default",
    "PRIMER_NOMBRE_IDENTITARIO" text COLLATE pg_catalog."default",
    "SEGUNDO_NOMBRE_IDENTITARIO" text COLLATE pg_catalog."default",
    "PRIMER_APELLIDO_IDENTITARIO" text COLLATE pg_catalog."default",
    "SEGUNDO_APELLIDO_IDENTITARIO" text COLLATE pg_catalog."default",
    "CODIGO_TIPO_IDENTIFICACION" text COLLATE pg_catalog."default",
    "TIPO_IDENTIFICACION" text COLLATE pg_catalog."default",
    "IDENTIFICACION_right" text COLLATE pg_catalog."default",
    "TIPO_GENERO" text COLLATE pg_catalog."default",
    "GENERO" text COLLATE pg_catalog."default",
    "CODIGO_TIPO_NACIONALIDAD" text COLLATE pg_catalog."default",
    "NACIONALIDAD" text COLLATE pg_catalog."default",
    "FECHA_DE_NACIMIENTO" text COLLATE pg_catalog."default",
    "EDAD" text COLLATE pg_catalog."default",
    "CODIGO_TIPO_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "TIPO_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "FALLECIDO" text COLLATE pg_catalog."default",
    "FECHA_DE_FALLECIMIENTO" text COLLATE pg_catalog."default",
    "LOGIN" text COLLATE pg_catalog."default",
    "CORREO_INSTITUCIONAL" text COLLATE pg_catalog."default",
    "CORREO_PERSONAL" text COLLATE pg_catalog."default",
    "TELEFONO_RESIDENCIA" text COLLATE pg_catalog."default",
    "TELEFONO_CELULAR" text COLLATE pg_catalog."default",
    "TELEFONO_TRABAJO" text COLLATE pg_catalog."default",
    "DIRECCION_RESIDENCIA" text COLLATE pg_catalog."default",
    "CODIGO_CIUDAD_RESIDENCIA" text COLLATE pg_catalog."default",
    "CIUDAD_RESIDENCIA" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO_RESIDENCIA" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_RESIDENCIA" text COLLATE pg_catalog."default",
    "CODIGO_PAIS_RESIDENCIA" text COLLATE pg_catalog."default",
    "PAIS_RESIDENCIA" text COLLATE pg_catalog."default",
    "DIRECCION_TRABAJO" text COLLATE pg_catalog."default",
    "CODIGO_CIUDAD_TRABAJO" text COLLATE pg_catalog."default",
    "CIUDAD_TRABAJO" text COLLATE pg_catalog."default",
    "CODIGO_DEPARTAMENTO_TRABAJO" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_TRABAJO" text COLLATE pg_catalog."default",
    "CODIGO_PAIS_TRABAJO" text COLLATE pg_catalog."default",
    "PAIS_TRABAJO" text COLLATE pg_catalog."default",
    "NOMBRE_PADRE" text COLLATE pg_catalog."default",
    "TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "NOMBRE_MADRE" text COLLATE pg_catalog."default",
    "TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "DIRECCION_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "TELEFONO_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "CORREO_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "INDICADOR_CONFIDENCIALIDAD" text COLLATE pg_catalog."default",
    "CIUDAD_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "PAIS_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "CIUDAD_TRABAJO_UG" text COLLATE pg_catalog."default",
    "DEPARTAMENTO_TRABAJO_UG" text COLLATE pg_catalog."default",
    "PAIS_TRABAJO_UG" text COLLATE pg_catalog."default",
    "CIUDAD_NACIMIENTO" text COLLATE pg_catalog."default",
    "ESTRATO" text COLLATE pg_catalog."default",
    "FACULTADES_right" text COLLATE pg_catalog."default",
    "CODIGO_FACULTAD_right" text COLLATE pg_catalog."default",
    "info_personas.PRIMER_NOMBRE" text COLLATE pg_catalog."default",
    "info_personas.SEGUNDO_NOMBRE" text COLLATE pg_catalog."default",
    "info_personas.NOMBRES" text COLLATE pg_catalog."default",
    "info_personas.PRIMER_APELLIDO" text COLLATE pg_catalog."default",
    "info_personas.SEGUNDO_APELLIDO" text COLLATE pg_catalog."default",
    "info_personas.APELLIDOS" text COLLATE pg_catalog."default",
    "info_personas.PRIMER_NOMBRE_IDENTITARIO" text COLLATE pg_catalog."default",
    "info_personas.SEGUNDO_NOMBRE_IDENTITARIO" text COLLATE pg_catalog."default",
    "info_personas.PRIMER_APELLIDO_IDENTITARIO" text COLLATE pg_catalog."default",
    "info_personas.SEGUNDO_APELLIDO_IDENTITARIO" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_TIPO_IDENTIFICACION" text COLLATE pg_catalog."default",
    "info_personas.TIPO_IDENTIFICACION" text COLLATE pg_catalog."default",
    "info_personas.IDENTIFICACION" text COLLATE pg_catalog."default",
    "info_personas.TIPO_GENERO" text COLLATE pg_catalog."default",
    "info_personas.GENERO" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_TIPO_NACIONALIDAD" text COLLATE pg_catalog."default",
    "info_personas.NACIONALIDAD" text COLLATE pg_catalog."default",
    "info_personas.FECHA_DE_NACIMIENTO" text COLLATE pg_catalog."default",
    "info_personas.EDAD" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_TIPO_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "info_personas.TIPO_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "info_personas.FALLECIDO" text COLLATE pg_catalog."default",
    "info_personas.FECHA_DE_FALLECIMIENTO" text COLLATE pg_catalog."default",
    "info_personas.LOGIN" text COLLATE pg_catalog."default",
    "info_personas.CORREO_INSTITUCIONAL" text COLLATE pg_catalog."default",
    "info_personas.CORREO_PERSONAL" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_CELULAR" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.DIRECCION_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_CIUDAD_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.CIUDAD_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_DEPARTAMENTO_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.DEPARTAMENTO_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_PAIS_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.PAIS_RESIDENCIA" text COLLATE pg_catalog."default",
    "info_personas.DIRECCION_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_CIUDAD_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.CIUDAD_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_DEPARTAMENTO_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.DEPARTAMENTO_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.CODIGO_PAIS_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.PAIS_TRABAJO" text COLLATE pg_catalog."default",
    "info_personas.NOMBRE_PADRE" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_PADRE" text COLLATE pg_catalog."default",
    "info_personas.NOMBRE_MADRE" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_MADRE" text COLLATE pg_catalog."default",
    "info_personas.REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "info_personas.DIRECCION_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "info_personas.TELEFONO_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "info_personas.CORREO_REPRESENTANTE_FINANCIERO" text COLLATE pg_catalog."default",
    "info_personas.INDICADOR_CONFIDENCIALIDAD" text COLLATE pg_catalog."default",
    "info_personas.CIUDAD_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "info_personas.DEPARTAMENTO_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "info_personas.PAIS_RESIDENCIA_UG" text COLLATE pg_catalog."default",
    "info_personas.CIUDAD_TRABAJO_UG" text COLLATE pg_catalog."default",
    "info_personas.DEPARTAMENTO_TRABAJO_UG" text COLLATE pg_catalog."default",
    "info_personas.PAIS_TRABAJO_UG" text COLLATE pg_catalog."default",
    "info_personas.CIUDAD_NACIMIENTO" text COLLATE pg_catalog."default",
    "info_personas.ESTRATO" text COLLATE pg_catalog."default",
    "info_personas.FACULTADES" text COLLATE pg_catalog."default",
    CONSTRAINT dim_profes_pkey PRIMARY KEY ("CODIGO_DOCENTE")
);


CREATE TABLE IF NOT EXISTS public.dim_grupo
(
    "ID_GRUPO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_grupo_pkey PRIMARY KEY ("ID_GRUPO")
);


CREATE TABLE IF NOT EXISTS public.dim_tipo_financiamiento
(
    "Índice" bigint,
    "SECCION_MOD" text COLLATE pg_catalog."default",
    CONSTRAINT dim_tipos_de_financiamiento_pkey PRIMARY KEY ("SECCION_MOD")
);

CREATE TABLE IF NOT EXISTS public.dim_union_grupo_tipo
(
    "ID_GRUPO" text COLLATE pg_catalog."default",
    "SECCION_PORCENTAJE" text COLLATE pg_catalog."default",
    "SECCION_MOD" text COLLATE pg_catalog."default",
    "PORCENTAJE_APORTE_ITEM" double precision,
    CONSTRAINT fk_grupo FOREIGN KEY ("ID_GRUPO")
        REFERENCES public.dim_grupo ("ID_GRUPO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_union_grupo_tipo_tf FOREIGN KEY ("SECCION_MOD")
        REFERENCES public.dim_tipo_financiamiento ("SECCION_MOD") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS public.dim_grupo_horario
(
    "ID_GRUPO_HORARIO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_grupo_horario_pkey PRIMARY KEY ("ID_GRUPO_HORARIO")
);

CREATE TABLE IF NOT EXISTS public.dim_horario
(
    "ID_HORARIO" double precision,
    "FECHA_INICIO_FRANJA" date,
    "FECHA_FIN_FRANJA" date,
    "HORA_INICIO_FRANJA" text COLLATE pg_catalog."default",
    "HORA_FIN_FRANJA" text COLLATE pg_catalog."default",
    "LUNES" text COLLATE pg_catalog."default",
    "MARTES" text COLLATE pg_catalog."default",
    "MIERCOLES" text COLLATE pg_catalog."default",
    "JUEVES" text COLLATE pg_catalog."default",
    "VIERNES" text COLLATE pg_catalog."default",
    "SABADO" text COLLATE pg_catalog."default",
    "DOMINGO" text COLLATE pg_catalog."default",
    CONSTRAINT dim_horario_pkey PRIMARY KEY ("ID_HORARIO")

);


CREATE TABLE IF NOT EXISTS public.dim_union_grupo_horario
(
    "PERIODO" text COLLATE pg_catalog."default",
    "CRN" text COLLATE pg_catalog."default",
    "FECHA_INICIO_FRANJA" date,
    "FECHA_FIN_FRANJA" date,
    "HORA_INICIO_FRANJA" text COLLATE pg_catalog."default",
    "HORA_FIN_FRANJA" text COLLATE pg_catalog."default",
    "LUNES" text COLLATE pg_catalog."default",
    "MARTES" text COLLATE pg_catalog."default",
    "MIERCOLES" text COLLATE pg_catalog."default",
    "JUEVES" text COLLATE pg_catalog."default",
    "VIERNES" text COLLATE pg_catalog."default",
    "SABADO" text COLLATE pg_catalog."default",
    "DOMINGO" text COLLATE pg_catalog."default",
    "ID_HORARIO" double precision,
    "ID_GRUPO_HORARIO" text COLLATE pg_catalog."default",
    CONSTRAINT fk_grupo_horario FOREIGN KEY ("ID_GRUPO_HORARIO")
        REFERENCES public.dim_grupo_horario ("ID_GRUPO_HORARIO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_union_grupo_tipo_horario FOREIGN KEY ("ID_HORARIO")
        REFERENCES public.dim_horario ("ID_HORARIO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);



-- Table: public.hechos_estudiante_curso_auxiliar

CREATE TABLE IF NOT EXISTS public.hechos_estudiante_curso
(
    "PERIODO" text COLLATE pg_catalog."default",
    "CODIGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "SECCION" text COLLATE pg_catalog."default",
    "CALIFICACION_PARCIAL" text COLLATE pg_catalog."default",
    "CALIFICACION_FINAL" text COLLATE pg_catalog."default",
    "CALIFICACION_PARCIAL_CONTEO" text COLLATE pg_catalog."default",
    "CALIFICACION_FINAL_CONTEO" text COLLATE pg_catalog."default",
    "ESTATUS_CURSO" text COLLATE pg_catalog."default",
    "RETIRO" text COLLATE pg_catalog."default",
    "NOTA_FINAL_MOD" double precision,
    "ESTADO_MATERIA_FINAL" text COLLATE pg_catalog."default",
    "dim_curso.ID_MATERIA" text COLLATE pg_catalog."default",
    "CRN" text COLLATE pg_catalog."default",
    "dim_curso.HORAS_CREDITO" text COLLATE pg_catalog."default",
    "dim_programa.ID_PROGRAMA" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_3" text COLLATE pg_catalog."default",
    "CODIGO_DOCENTE" text COLLATE pg_catalog."default",
    "ID_GRUPO_HORARIO" text COLLATE pg_catalog."default",
    CONSTRAINT fk_curso FOREIGN KEY ("dim_curso.ID_MATERIA")
        REFERENCES public.dim_curso ("ID_MATERIA") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_docente FOREIGN KEY ("CODIGO_DOCENTE")
        REFERENCES public.dim_profesor ("CODIGO_DOCENTE") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_periodo FOREIGN KEY ("PERIODO")
        REFERENCES public.dim_periodo ("ANIO_PERIODO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_programa FOREIGN KEY ("dim_programa.ID_PROGRAMA")
        REFERENCES public.dim_programa ("ID_PROGRAMA") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_estudiante FOREIGN KEY ("CODIGO_ESTUDIANTE")
        REFERENCES public.dim_estudiantes ("CODIGO_ESTUDIANTE") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_grupo_horario FOREIGN KEY ("ID_GRUPO_HORARIO")
        REFERENCES public.dim_grupo_horario ("ID_GRUPO_HORARIO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.hechos_info_academica
(
    "PERIODO" text COLLATE pg_catalog."default",
    "CODIGO_ESTUDIANTE" text COLLATE pg_catalog."default",
    "CODIGO_ESTADO_ACADEMICO" text COLLATE pg_catalog."default",
    "DESCRIPCION_ESTADO_ACADEMICO" text COLLATE pg_catalog."default",
    "SSC" double precision,
    "CREDITO_SEM" double precision,
    "CREDITO_SEM_INTENTADO_INSTITUCIONAL" double precision,
    "CREDITO_SEM_APROBADO_INSTITUCIONAL" double precision,
    "CREDITO_SEM_PGA_INSTITUCIONAL" double precision,
    "PROMEDIO_SEM_INSTITUCIONAL" double precision,
    "CREDITO_SEM_INTENTADO_TRANSFERENCIA" double precision,
    "CREDITO_SEM_APROBADO_TRANSFERENCIA" double precision,
    "CREDITO_SEM_PGA_TRANSFERENCIA" double precision,
    "PROMEDIO_SEM_TRANSFERENCIA" double precision,
    "CREDITO_INTENTADO_GLOBAL" double precision,
    "CREDITO_APROBADO_GLOBAL" double precision,
    "CREDITO_PGA_GLOBAL" double precision,
    "PROMEDIO_GLOBAL" double precision,
    "OPCION_DE_GRADO" text COLLATE pg_catalog."default",
    "PROMEDIO_ACUM_INSTITUCIONAL" double precision,
    "PROMEDIO_SEM_GLOBAL" double precision,
    "CREDITO_SEM_GLOBAL" double precision,
    "PROMEDIO_ACUM_TRANSFERENCIA" double precision,
    "PUNTOS_CALIDAD_SEM" double precision,
    "PUNTOS_CALIDAD_ACUM" double precision,
    "NUMERO_CRN_RETIRADOS" double precision,
    "TOTAL_CREDIT_RETIRADOS_SEM" double precision,
    "CREDITO_SEM_INTENTADO_TOTAL" integer,
    "CODIGO_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_1" text COLLATE pg_catalog."default",
    "CODIGO_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_2" text COLLATE pg_catalog."default",
    "CODIGO_PROGRAMA_3" text COLLATE pg_catalog."default",
    "CODIGO_NIVEL_PROGRAMA_3" text COLLATE pg_catalog."default",
    "ID_PROGRAMA" text COLLATE pg_catalog."default",
    "PERIODO_COPIA" text COLLATE pg_catalog."default",
    "CODIGO_ESTUDIANTE_COPIA" text COLLATE pg_catalog."default",
    "PERIODO_CODIGO" text COLLATE pg_catalog."default",
    "ID_GRUPO" text COLLATE pg_catalog."default",
    "SEMESTRES_NO_MATRICULADOS" bigint,
    "INACTIVO_DESERTOR_ACTIVO" text COLLATE pg_catalog."default",
    "MATRICULADO_SEMESTRE_MAS_RECIENTE" text COLLATE pg_catalog."default",
    "GRADUADO_DO" text COLLATE pg_catalog."default",
    "GRADUADO_MA" text COLLATE pg_catalog."default",
    "GRADUADO_PR" text COLLATE pg_catalog."default",
    "CREDITOS_APROBADOS" double precision,
    "CREDITOS_REPROBADOS" double precision,
    "CREDITOS_RETIRADOS" double precision,
    "CREDITOS_INCOMPLETOS" double precision,
    "TOTAL_CREDITOS" double precision,
    "TOTAL_SEMESTRES_MATRICULADOS" double precision,
    CONSTRAINT fk_grupo_financiero FOREIGN KEY ("ID_GRUPO")
        REFERENCES public.dim_grupo ("ID_GRUPO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_periodo FOREIGN KEY ("PERIODO")
        REFERENCES public.dim_periodo ("ANIO_PERIODO") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_programa_info_academica FOREIGN KEY ("ID_PROGRAMA")
        REFERENCES public.dim_programa ("ID_PROGRAMA") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_estudiante FOREIGN KEY ("CODIGO_ESTUDIANTE")
        REFERENCES public.dim_estudiantes ("CODIGO_ESTUDIANTE") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

